# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.8.4-base

# build-time tokens for gated downloads — never baked into final image.
# pass via: docker build --build-arg HF_TOKEN=$HF_TOKEN ...
ARG HF_TOKEN=""

# install custom nodes into comfyui
RUN comfy node install --exit-on-fail comfyui-kjnodes@1.3.5 --mode remote || (echo "WARN: comfyui-kjnodes@1.3.5 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-kjnodes --mode remote)
RUN comfy node install --exit-on-fail comfyui-easy-use@1.3.6 || (echo "WARN: comfyui-easy-use@1.3.6 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-easy-use)
RUN comfy node install --exit-on-fail comfyui_memory_cleanup@1.1.3 || (echo "WARN: comfyui_memory_cleanup@1.1.3 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui_memory_cleanup)
RUN git clone https://github.com/lihaoyun6/ComfyUI-llama-cpp_vlm /comfyui/custom_nodes/ComfyUI-llama-cpp_vlm && cd /comfyui/custom_nodes/ComfyUI-llama-cpp_vlm && (git checkout 2d28817e12f912ec9e27ce83cf7610a477152185 2>/dev/null || (git fetch origin 2d28817e12f912ec9e27ce83cf7610a477152185 --depth=1 && git checkout 2d28817e12f912ec9e27ce83cf7610a477152185) || echo "WARN: commit 2d28817e12f912ec9e27ce83cf7610a477152185 unreachable in https://github.com/lihaoyun6/ComfyUI-llama-cpp_vlm, falling back to default branch HEAD")
RUN comfy node install --exit-on-fail comfyui-custom-scripts@1.2.5 || (echo "WARN: comfyui-custom-scripts@1.2.5 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-custom-scripts)
RUN comfy node install --exit-on-fail was-ns@3.0.0 || (echo "WARN: was-ns@3.0.0 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail was-ns)
RUN git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && cd /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && (git checkout 8923bd836bdab8b7bbdf4ed104b7d045e70c66e2 2>/dev/null || (git fetch origin 8923bd836bdab8b7bbdf4ed104b7d045e70c66e2 --depth=1 && git checkout 8923bd836bdab8b7bbdf4ed104b7d045e70c66e2) || echo "WARN: commit 8923bd836bdab8b7bbdf4ed104b7d045e70c66e2 unreachable in https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite, falling back to default branch HEAD")
RUN comfy node install --exit-on-fail rgthree-comfy
RUN git clone https://github.com/landon2022/LTX2EasyPrompt-LD /comfyui/custom_nodes/LTX2EasyPrompt-LD

# download models into comfyui
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Kijai/LTX2.3_comfy/resolve/main/vae/LTX23_audio_vae_bf16.safetensors?download=true' --relative-path models/vae --filename 'LTX23_audio_vae_bf16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/lynaNSFW/gemma-3-12b-it-heretic-v2_fp8_e4m3fn/resolve/main/gemma-3-12b-it-heretic-v2_fp8_e4m3fn.safetensors' --relative-path models/text_encoders --filename 'gemma-3-12b-it-heretic-v2_fp8_e4m3fn.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/onewayomni/ltx-2.3_text_projection_bf16.safetensors/resolve/main/ltx-2.3_text_projection_bf16.safetensors' --relative-path models/text_encoders --filename 'ltx-2.3_text_projection_bf16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Kijai/LTX2.3_comfy/resolve/main/vae/taeltx2_3.safetensors' --relative-path models/vae --filename 'taeltx2_3.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/vae/hunyuan_video_vae_bf16.safetensors' --relative-path models/vae --filename 'LTX23_video_vae_bf16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/darksidewalker/DaSiWa-LTX2.3/resolve/main/Non-Distilled/FP8/v03/DasiwaLTX23_goldenLaceV3-fp8.safetensors?download=true' --relative-path models/diffusion_models --filename 'ltx/DasiwaLTX23Lightspeed_treasurechestV1.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-spatial-upscaler-x2-1.0.safetensors' --relative-path models/latent_upscale_models --filename 'ltx-2-spatial-upscaler-x2-1.0.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-spatial-upscaler-x2-1.0.safetensors' --relative-path models/upscale_models --filename 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/prithivMLmods/Qwen3.5-abliterated-MAX-AIO-GGUF/resolve/main/Qwen3.5-9B-Unredacted-MAX-GGUF/Qwen3.5-9B-Unredacted-MAX.Q8_0.gguf' --relative-path models/Unknown --filename 'F:/comfy/ComfyUI_windows_portable/ComfyUI/models/LLM/Qwen3.5-9B-f32-GGUF/Qwen3.5-9B-Unredacted-MAX.Q8_0.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/prithivMLmods/Qwen3.5-abliterated-MAX-AIO-GGUF/resolve/main/Qwen3.5-9B-Unredacted-MAX-GGUF/Qwen3.5-9B-Unredacted-MAX.Q8_0.gguf' --relative-path models/Unknown --filename 'Qwen3.5-9B-f32-GGUF/Qwen3.5-9B-Unredacted-MAX.Q8_0.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/prithivMLmods/Qwen3.5-abliterated-MAX-AIO-GGUF/resolve/main/Qwen3.5-9B-Unredacted-MAX-GGUF/Qwen3.5-9B-Unredacted-MAX.mmproj-bf16.gguf' --relative-path models/Unknown --filename 'Qwen3.5-9B-f32-GGUF/Qwen3.5-9B-Unredacted-MAX.mmproj-bf16.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done

# copy all input data (like images or videos) into comfyui (uncomment and adjust if needed)
# COPY input/ /comfyui/input/

# user-provided inputs override the auto-generated placeholders above.
RUN wget --progress=dot:giga -O '/comfyui/input/ComfyUI_02167_.png' "https://cool-anteater-319.convex.cloud/api/storage/4fcdc512-9813-43bd-8187-15898536955d"
